### ISSUE TITLE
in cv4 have problem

### ISSUE THREAD

**Issue by Mahdi-Ba** [pmathur5k10/Credit-Card-Recognition#3]
_a_reference.png
Traceback (most recent call last):
  File "ocr_template_match.py", line 104, in <module>
    (x, y, w, h) = cv2.boundingRect(c)
cv2.error: OpenCV(4.2.0) /io/opencv/modules/imgproc/src/shapedescr.cpp:784: error: (-215:Assertion failed) npoints >= 0 && (depth == CV_32F || depth == CV_32S) in function 'pointSetBoundingRect'

**Comment by KTibow** [comment]
I think it might need to be a different color space. Here's your log formatted:
```
Traceback (most recent call last):
File "ocr_template_match.py", line 104, in
(x, y, w, h) = cv2.boundingRect(c)
cv2.error: OpenCV(4.2.0) /io/opencv/modules/imgproc/src/shapedescr.cpp:784: error: (-215:Assertion failed) npoints >= 0 && (depth == CV_32F || depth == CV_32S) in function 'pointSetBoundingRect'
```
